# Generated by Django 2.1.2 on 2018-10-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenos',
            new_name='lineos',
        ),
    ]
